# Generated by Django 3.2.10 on 2021-12-21 21:54

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='source_cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF do usuário indicador'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='target_cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, unique=True, verbose_name='CPF da pessoa indicada'),
        ),
    ]
