# Generated by Django 3.2.10 on 2021-12-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_auto_20211221_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
